####ln -snf ~/dotfiles/.bashrc ~/.bashrc
####ln -snf ~/dotfiles/.bash_profile ~/.bash_profile
ln -snf ~/dotfiles/fishfile ~/.config/fish/fishfile
ln -snf ~/dotfiles/config.fish ~/.config/fish/config.fish
ln -snf ~/dotfiles/.vimrc ~/.vimrc
ln -snf ~/dotfiles/.vimrc.basic ~/.vimrc.basic
ln -snf ~/dotfiles/.vimrc.edit ~/.vimrc.edit
ln -snf ~/dotfiles/.vimrc.apperance ~/.vimrc.apperance
ln -snf ~/dotfiles/.vimrc.plug ~/.vimrc.plug
ln -snf ~/dotfiles/.vimrc.moving ~/.vimrc.moving
ln -snf ~/dotfiles/.gitconfig ~/.gitconfig
ln -snf ~/dotfiles/.tigrc ~/.tigrc
